host = "0.0.0.0"
port = 7999
allowed_cors_domains = [
    "http://localhost:7999",
    "https://localhost:7999"
]

[db_settings]
connection_string = "postgresql+asyncpg://postgres:testpwd123@localhost:5433/demo_db"
